# Generated by Django 5.0.2 on 2024-02-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(verbose_name='Ürün Açıklaması'),
        ),
    ]
